/*
 * Copyright (c) 2020-21, Kalopa Robotics Limited.  All rights
 * reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ABSTRACT
 * All radio communications happens here.
 * 434.00 to 434.80 MHz.
 */
#include <stdio.h>
#include <avr/io.h>
#include <avr/pgmspace.h>

#include <libavr.h>

#include "libradio.h"
#include "radio.h"
#include "radio_config.h"

const uchar_t	radio_config[] PROGMEM = RADIO_CONFIGURATION_DATA_ARRAY;

void
_myflush()
{
	while (!sio_oqueue_empty())
		;
}

/*
 * Power up the rp-> Configure the frequencies, and let's get going. The
 * key here is the block of data defined in the radio_config.h file. This
 * file is auto-generated by the "Wireless Development Suite" from Silicon
 * Labs. It is a GUI used to define the parameters and the result is a set
 * of length/value coded values (RADIO_CONFIGURATION_DATA_ARRAY) to be sent
 * to the chip. We keep the array in program memory to save on RAM. The
 * bulk of the config happens here. The last step is to do an IR
 * calibration which is known to take up to a few seconds, so we wait...
 */
int
libradio_power_up(struct libradio *rp)
{
	uchar_t i, len;
	int addr;

	printf(">>> Radio power-up... %d\n", sizeof(radio_config));
	addr = 0;
	while ((len = pgm_read_byte(&radio_config[addr++])) != 0) {
		for (i = 0; i < len; i++)
			spi_data[i] = pgm_read_byte(&radio_config[addr++]);
		if (spi_send(len, 0) == 0) {
			libradio_set_state(rp, LIBRADIO_STATE_ERROR);
			return(-1);
		}
	}
	libradio_get_chip_status(rp);
	libradio_get_part_info(rp);
	libradio_get_chip_status(rp);
	libradio_get_func_info(rp);
	libradio_get_chip_status(rp);
	libradio_ircal(rp);
	libradio_get_chip_status(rp);
	libradio_request_device_status(rp);
	libradio_get_chip_status(rp);
	rp->radio_active = 1;
	printf("Good.\n");
	return(0);
}
