/*
 * Copyright (c) 2020-24, Kalopa Robotics Limited.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ABSTRACT
 * All radio initialization happens here. We keep the configuration
 * data in program memory, in the RADIO_CONFIGURATION_DATA_ARRAY. The
 * specifics of the radio operation are defined in the radio_config.h
 * file which is generated by a third-party application program and is
 * outside the scope of this system. Suffice to say, the radio operates
 * at a frequency of 434.00 to 434.80 MHz. As it took a lot of trial
 * and error to get that stuff configured and to get the radio to Do
 * The Right Thing, I'd advise staying clear of that parameter set.
 */
#include <stdio.h>
#include <avr/io.h>
#include <avr/pgmspace.h>

#include <libavr.h>

#include "libradio.h"
#include "internal.h"
#include "radio_config.h"

const uchar_t	radio_config[] PROGMEM = RADIO_CONFIGURATION_DATA_ARRAY;

/*
 * Power up the radio. Configure the frequencies, and let's get going. The
 * key here is the block of data defined in the radio_config.h file. This
 * file is auto-generated by the "Wireless Development Suite" from Silicon
 * Labs. It is a GUI used to define the parameters and the result is a set
 * of length/value coded values (RADIO_CONFIGURATION_DATA_ARRAY) to be sent
 * to the chip. We keep the array in program memory to save on RAM. The
 * bulk of the config happens here. The last step is to do an IR
 * calibration which is known to take up to a few seconds, so we wait...
 */
int
libradio_power_up()
{
	uchar_t i, len;
	int addr;

	addr = 0;
	if (radio.radio_active)
		return(0);
	printf("PowerUp!\n");
	while ((len = pgm_read_byte(&radio_config[addr++])) != 0) {
		for (i = 0; i < len; i++)
			spi_data[i] = pgm_read_byte(&radio_config[addr++]);
		if ((i = spi_send(len, 0)) != SPI_SEND_OK) {
			spi_error(i);
			libradio_set_state(LIBRADIO_STATE_ERROR);
			return(-1);
		}
	}
	libradio_get_chip_status();
	libradio_get_part_info();
	libradio_get_func_info();
	libradio_get_int_status();
	libradio_ircal();
	libradio_request_device_status();
	libradio_get_fifo_info(03);
	printf("Radio Active\n");
	radio.radio_active = 1;
	return(0);
}

/*
 * Power-down the radio. Right now, this does nothing. It would be great
 * if there was something useful we could do, here. Sometimes the radio
 * ends up in a weird state and only power-cycling the entire system
 * can fix it.
 */
void
libradio_power_down()
{
	radio.radio_active = 0;
}
